[build]
  base = "apps/web"
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish = ".next"

  [build.environment]
    NODE_VERSION = "20.14"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
