# netlify.toml
[build]
publish = "apps/web/.next"
# Netlify will do the install step once; we only run the build
command = "corepack enable && pnpm --filter web build"

[build.environment]
NODE_VERSION = "20.12.2"
PNPM_VERSION = "9.12.3"
PNPM_CONFIG_FROZEN_LOCKFILE = "false"   # allow install without a lockfile
